import django
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pizza.settings")
django.setup()

from inventory.models import *
from accounts.models import *

piz1 = Pizza(pizza_type="Regular", size="Small", price=12.70)
piz1.save()
piz2 = Pizza(pizza_type="Regular", size="Large", price=17.95)
piz2.save()
piz3 = Pizza(pizza_type="Silician", size="Small", price=24.45)
piz3.save()
piz4 = Pizza(pizza_type="Silician", size="Large", price=38.70)
piz4.save()

toppings_list = ["Pepperoni","Sausage","Mushrooms","Onions","Ham","Canadian Bacon","Pineapple","Eggplant","Tomato & Basil","Green Peppers","Hamburger","Spinach","Artichoke","Buffalo Chicken","Barbecue Chicken","Anchovies","Black Olives","Fresh Garlic","Zucchini"]

for top in toppings_list:
    t = Topping(name=top)
    t.save()
	
sub1 = Sub(sub_type="Cheese", size="Small", price=6.50)
sub1.save()
sub2 = Sub(sub_type="Cheese", size="Large", price=7.95)
sub2.save()
sub3 = Sub(sub_type="Italian", size="Small", price=6.50)
sub3.save()
sub4 = Sub(sub_type="Italian", size="Large", price=7.95)
sub4.save()
sub5 = Sub(sub_type="Ham + Cheese", size="Small", price=6.50)
sub5.save()
sub6 = Sub(sub_type="Ham + Cheese", size="Large", price=7.95)
sub6.save()
sub7 = Sub(sub_type="Meatball", size="Small", price=6.50)
sub7.save()
sub8 = Sub(sub_type="Meatball", size="Large", price=7.95)
sub8.save()
sub9 = Sub(sub_type="Tuna", size="Small", price=6.50)
sub9.save()
sub10 = Sub(sub_type="Tuna", size="Large", price=7.95)
sub10.save()
sub11 = Sub(sub_type="Turkey", size="Small", price=7.50)
sub11.save()
sub12 = Sub(sub_type="Turkey", size="Large", price=8.50)
sub12.save()
sub13 = Sub(sub_type="Chicken Parmigiana", size="Small", price=7.50)
sub13.save()
sub14 = Sub(sub_type="Chicken Parmigiana", size="Large", price=8.50)
sub14.save()
sub15 = Sub(sub_type="Eggplant Parmigiana", size="Small", price=6.50)
sub15.save()
sub16 = Sub(sub_type="Eggplant Parmigiana", size="Large", price=7.95)
sub16.save()
sub17 = Sub(sub_type="Steak", size="Small", price=6.50)
sub17.save()
sub18 = Sub(sub_type="Steak", size="Large", price=7.95)
sub18.save()
sub19 = Sub(sub_type="Steak + Cheese", size="Small", price=6.95)
sub19.save()
sub20 = Sub(sub_type="Steak + Cheese", size="Large", price=8.50)
sub20.save()
sub21 = Sub(sub_type="Sausage, Peppers & Onions", size="Large", price=8.50)
sub21.save()
sub22 = Sub(sub_type="Hamburger", size="Small", price=4.60)
sub22.save()
sub23 = Sub(sub_type="Hamburger", size="Large", price=6.95)
sub23.save()
sub24 = Sub(sub_type="Cheeseburger", size="Small", price=5.10)
sub24.save()
sub25 = Sub(sub_type="Cheeseburger", size="Large", price=7.45)
sub25.save()
sub26 = Sub(sub_type="Fried Chicken", size="Small", price=6.95)
sub26.save()
sub27 = Sub(sub_type="Fried Chicken", size="Large", price=8.50)
sub27.save()
sub28 = Sub(sub_type="Veggie", size="Small", price=6.95)
sub28.save()
sub29 = Sub(sub_type="Veggie", size="Large", price=8.50)
sub29.save()
pa1 = Pasta(name="Baked Ziti w/Mozzarella", price=6.50)
pa1.save()
pa2 = Pasta(name="Baked Ziti w/Meatballs", price=8.75)
pa2.save()
pa3 = Pasta(name="Baked Ziti w/Chicken", price=9.75)
pa3.save()
s1 = Salad(name="Garden Salad", price=6.25)
s1.save()
s2 = Salad(name="Greek Salad", price=8.25)
s2.save()
s3 = Salad(name="Antipasto", price=8.25)
s3.save()
s4 = Salad(name="Salad w/Tuna", price=8.25)
s4.save()
dp1 = Dinner_Platter(dinner_platters_type="Garden Salad", size="Small", price=35)
dp1.save()
dp2 = Dinner_Platter(dinner_platters_type="Garden Salad", size="Large", price=60)
dp2.save()
dp3 = Dinner_Platter(dinner_platters_type="Greek Salad", size="Small", price=45)
dp3.save()
dp4 = Dinner_Platter(dinner_platters_type="Greek Salad", size="Large", price=70)
dp4.save()
dp5 = Dinner_Platter(dinner_platters_type="Antipasto", size="Small", price=45)
dp5.save()
dp6 = Dinner_Platter(dinner_platters_type="Antipasto", size="Large", price=70)
dp6.save()
dp7 = Dinner_Platter(dinner_platters_type="Baked Ziti", size="Small", price=35)
dp7.save()
dp8 = Dinner_Platter(dinner_platters_type="Baked Ziti", size="Large", price=60)
dp8.save()
dp9 = Dinner_Platter(dinner_platters_type="Meatball Parm", size="Small", price=45)
dp9.save()
dp10 = Dinner_Platter(dinner_platters_type="Meatball Parm", size="Large", price=70)
dp10.save()
dp11 = Dinner_Platter(dinner_platters_type="Chicken Parm", size="Small", price=45)
dp11.save()
dp12 = Dinner_Platter(dinner_platters_type="Chicken Parm", size="Large", price=80)
dp12.save()

user1 = Account(username="achraf", password="pbkdf2_sha256$150000$bDlH8OEuTysb$m2v6Rbg7eeRIVJ9cyq/cJwhXrWFwaScXwg66/ThQ5Ww=", email="achraf.adbib@hotmail.com")
user1.save()
user2 = Account(username="admin", password="pbkdf2_sha256$150000$bDlH8OEuTysb$m2v6Rbg7eeRIVJ9cyq/cJwhXrWFwaScXwg66/ThQ5Ww=", email="test@test.com")
user2.is_admin = True
user2.is_staff = True
user2.is_superuser = True
user2.save()

