# Generated by Django 2.2.7 on 2019-11-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(default='Pasta', max_length=15)),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(default='Salad', max_length=15)),
                ('name', models.CharField(max_length=24)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('food_type', models.CharField(default='Topping', max_length=15)),
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(default='Sub', max_length=15)),
                ('sub_type', models.CharField(max_length=32)),
                ('size', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField()),
            ],
            options={
                'unique_together': {('sub_type', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(default='Pizza', max_length=15)),
                ('pizza_type', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField()),
            ],
            options={
                'unique_together': {('pizza_type', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Dinner_Platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(default='Platter', max_length=15)),
                ('dinner_platters_type', models.CharField(max_length=24)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size', models.CharField(max_length=6)),
                ('slug', models.SlugField()),
            ],
            options={
                'unique_together': {('dinner_platters_type', 'size')},
            },
        ),
    ]
